[package]
name = "surveyor-gnc"
version = "0.1.0"
edition = "2021"
description = "A simple GNC flight software implementation using bevy-ecs"

[dependencies]
bevy_app = "0.12"
bevy_ecs = "0.12"
chrono = "0.4.26"
dashmap = "5.4.0"
log = "0.4.19"
nalgebra = "0.32.2"
bevy-debug-text-overlay = "7.0.0"
